### ISSUE TITLE
Android Studio 

### ISSUE THREAD

**Issue by John9670** [John9670/Attend-In#1]
Getting to know Android Studio

**Comment by ambear-g** [comment]
Take some time to learn more about Android Studio and how it works
- Download Android Studio
- Use the newest version (try to stick to a low-mid range level for now)
   - Make sure we all learn the newest version

**Comment by vpatel04** [comment]
I downloaded Android Studio and I am posting a link here for the Mac users. 
The version I downloaded is 4.1.2 for Mac (877 MiB). 
https://developer.android.com/studio#downloads
