### ISSUE TITLE
Google FireStore

### ISSUE THREAD

**Issue by John9670** [John9670/Attend-In#2]
Getting to know Google FireStore

**Comment by ambear-g** [comment]
Do more research on how Google FireStore works
- What tools do we need to get FireStore
- How do we implement FireStore
- How can we use it in our app?
- Features of FireStore
- See if R/SQL will affect this

**Comment by Lwang51** [comment]
We need a list of data that you app will gather. Then with that list, we will decide what tools form the database to use. This is a crucial step, because if we chose the wrong tools to use, it will be hard later on to change it. this is what the Microsoft guy from the Azure boot camp said.
