### ISSUE TITLE
App Modeling/Conceptual Model

### ISSUE THREAD

**Issue by John9670** [John9670/Attend-In#4]
Drawing a model

**Comment by Jpopo** [comment]
Can you see this Comment? haha smelly

**Comment by ambear-g** [comment]
- Coming up with an UI for the app
      - different layers of the app
- Different components that will make up the app (i.e. Firestorm, Android Studios ...)
- 

Make sure to keep it simple, we have to code it and make it easy for everyone to understand the code and easy to use the app

**Comment by vpatel04** [comment]
![Screen Shot 2021-02-23 at 7.57.21 PM.png](https://images.zenhubusercontent.com/6018b35f81aef3fb9df12bb3/306fd3ae-57cb-405c-91c7-6ffb24eec10f)
