### ISSUE TITLE
R and SQL for Database

### ISSUE THREAD

**Issue by Lwang51** [John9670/Attend-In#7]

**Comment by ambear-g** [comment]
I did some research on SQL and posted a file on Github with the findings.

**Comment by vpatel04** [comment]
Sql Research from Ambear-W
SQL -> Structured Query Language 
  - a databases (think of getters from Java)
  - you can use it to set up databases and retrieve data, update, delete, create and more.  If you need to come out with anything, think of tables with columns that
        holds data that you grab by using certain call words.
  - This storage of data is done on a table

  These videos do a very good job of giving a simple explaination and example of what SQL is:
   - https://www.youtube.com/watch?v=27axs9dO7AE
   - https://www.youtube.com/watch?v=OfM5lC-7R4Y&t=186s

   Here are two links for more understanding
     - https://www.w3schools.com/sql/
     - http://www.sqlcourse.com/intro.html
