### ISSUE TITLE
Learn more About Agile Workflow

### ISSUE THREAD

**Issue by ambear-g** [John9670/Attend-In#8]
- What is a Scrum Master?
- What is a product manager?
- What is a programmer?
- What are sprints?
- What are epics
- Chapter 3

**Comment by ambear-g** [comment]
Hi guys!  Here are some shorter videos about agile that might be easier to understand than the lecture the Professor has posted!

I've also thought about seeing if my Product Manager and Scrum Master would like to answer some questions from you guys, but I wanted to see what yall thought before I pitched the idea!  So let me know!!!  (I'll also send a message over discord as well!))

video about agile project management:
https://www.youtube.com/watch?v=zi7uGg6FVM4

a more detailed video about agile:
https://www.youtube.com/watch?v=GzzkpAOxHXs

**Comment by vpatel04** [comment]
Hey guys, I watched the lecture video and I went through the slides of ch2,3. It gave me a brief idea on how agile works.
